backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Visible", name: "visible", widget: "boolean", default: false }
